#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countSwaps' function below.
#
# The function accepts INTEGER_ARRAY a as parameter.
#

def countSwaps(a):
    leng = len(a)
    swap = 0
    for i in range (leng):
        for j in range(leng -1):
            # print(a[j] , a[j+1])
            if a[j] > a[j+ 1]:
                swap += 1
                a[j+1], a[j] = a[j] , a[j+1]
    print(f"Array is sorted in {swap} swaps.\nFirst Element: {a[0]}\nLast Element: {a[-1]}")
                
                 

if __name__ == '__main__':
    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    countSwaps(a)
